CREATE TABLE CUSTOMER 
(
CUSTOMER_ID				INT PRIMARY KEY,
NAME					VARCHAR(20),
SOBRENOME				VARCHAR(30),
EMAIL					VARCHAR(30),
SEXO					VARCHAR(1),
DATA_NASCIMENTO			DATE,
TELEFONE				NVARCHAR,
TIPO_CLIENTE			VARCHAR(20)

)
--DROP TABLE IF EXISTS ORDERS
CREATE TABLE ORDERS
(
ORDER_ID				INT PRIMARY KEY,
ORDER_DATE				DATE,
ITEM_ID					INT,
CUSTOMER_ID				INT,
VALOR_ORDER				FLOAT
)
CREATE TABLE ITEM
(
ITEM_ID					INT,
ITEM_NOME				VARCHAR(20),
CATEGORY_ID				INT,
STATUS_ITEM				VARCHAR(20),
DATA_CANCELAMENTO		DATE
)
CREATE TABLE CATEGORY
(
CATEGORY_ID				INT,
CATEGORY_NAME			VARCHAR(20),
CATEGORY_TYPE			VARCHAR(20),
DESCRICAO				VARCHAR(20)
)
